/**
 * MCP debug database table metadata definitions.
 */
import type { DatabaseDebugTableDefinition } from "./mcp-debug-database-types";
export const databaseDebugTableDefinitions: DatabaseDebugTableDefinition[] = [
  {
    tableName: "WorkspaceUser",
    toolName: "debug_read_user_table",
    purpose:
      "Stores Local Playground users identified by Azure tenant and principal; parent row for per-user persisted data.",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "INTEGER",
        nullable: false,
        description: "Internal auto-increment primary key.",
      },
      {
        name: "tenantId",
        type: "TEXT",
        nullable: false,
        description: "Azure tenant ID for the signed-in account.",
      },
      {
        name: "principalId",
        type: "TEXT",
        nullable: false,
        description: "Azure principal/object ID for the signed-in account.",
      },
      {
        name: "lastUsedAt",
        type: "TEXT",
        nullable: false,
        description: "Last timestamp when this user was used for Azure session login.",
      },
    ],
  },
  {
    tableName: "AzureSelectionPreference",
    toolName: "debug_read_azure_selection_preference_table",
    purpose:
      "Stores last-used Azure project/deployment preferences and theme per user.",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "INTEGER",
        nullable: false,
        description: "Internal auto-increment primary key.",
      },
      {
        name: "userId",
        type: "INTEGER",
        nullable: false,
        description: "Foreign key to WorkspaceUser.id (one row per user).",
      },
      {
        name: "projectId",
        type: "TEXT",
        nullable: false,
        description: "Selected Azure project identifier.",
      },
      {
        name: "deploymentName",
        type: "TEXT",
        nullable: false,
        description: "Selected deployment name for chat execution.",
      },
      {
        name: "theme",
        type: "TEXT",
        nullable: false,
        description: "Selected theme value (light or dark).",
      },
      {
        name: "utilityProjectId",
        type: "TEXT",
        nullable: false,
        description: "Selected utility project identifier.",
      },
      {
        name: "utilityDeploymentName",
        type: "TEXT",
        nullable: false,
        description: "Selected utility deployment name.",
      },
      {
        name: "utilityReasoningEffort",
        type: "TEXT",
        nullable: false,
        description: "Reasoning effort for utility requests (for example high).",
      },
    ],
  },
  {
    tableName: "WorkspaceMcpServerProfile",
    toolName: "debug_read_workspace_mcp_server_profile_table",
    purpose:
      "Stores reusable MCP server profiles saved by each user (HTTP/SSE/stdio transport settings).",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "TEXT",
        nullable: false,
        description: "Stable profile ID.",
      },
      {
        name: "userId",
        type: "INTEGER",
        nullable: false,
        description: "Foreign key to WorkspaceUser.id.",
      },
      {
        name: "profileOrder",
        type: "INTEGER",
        nullable: false,
        description: "Display order in MCP Servers tab.",
      },
      {
        name: "connectOnThreadCreate",
        type: "BOOLEAN",
        nullable: false,
        description: "Whether this saved profile is auto-attached when creating a new thread.",
      },
      {
        name: "configKey",
        type: "TEXT",
        nullable: false,
        description: "Normalized key used to detect duplicate configurations.",
      },
      {
        name: "name",
        type: "TEXT",
        nullable: false,
        description: "User-facing profile name.",
      },
      {
        name: "transport",
        type: "TEXT",
        nullable: false,
        description: "Transport type: streamable_http, sse, or stdio.",
      },
      {
        name: "url",
        type: "TEXT",
        nullable: true,
        description: "HTTP/SSE endpoint URL when transport is remote.",
      },
      {
        name: "headersJson",
        type: "TEXT",
        nullable: true,
        description: "Serialized custom HTTP headers JSON.",
      },
      {
        name: "useAzureAuth",
        type: "BOOLEAN",
        nullable: false,
        description: "Whether bearer token injection with DefaultAzureCredential is enabled.",
      },
      {
        name: "azureAuthScope",
        type: "TEXT",
        nullable: true,
        description: "Azure token scope used when useAzureAuth is true.",
      },
      {
        name: "timeoutSeconds",
        type: "INTEGER",
        nullable: true,
        description: "Per-server timeout in seconds for remote transports.",
      },
      {
        name: "command",
        type: "TEXT",
        nullable: true,
        description: "Executable command when transport is stdio.",
      },
      {
        name: "argsJson",
        type: "TEXT",
        nullable: true,
        description: "Serialized command arguments JSON for stdio transport.",
      },
      {
        name: "cwd",
        type: "TEXT",
        nullable: true,
        description: "Working directory for stdio transport.",
      },
      {
        name: "envJson",
        type: "TEXT",
        nullable: true,
        description: "Serialized environment variable map JSON for stdio transport.",
      },
    ],
  },
  {
    tableName: "WorkspaceSkillRegistryProfile",
    toolName: "debug_read_workspace_skill_registry_profile_table",
    purpose:
      "Stores per-user Skill registry master rows used to classify and group installed Skills.",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "INTEGER",
        nullable: false,
        description: "Internal auto-increment primary key.",
      },
      {
        name: "userId",
        type: "INTEGER",
        nullable: false,
        description: "Foreign key to WorkspaceUser.id.",
      },
      {
        name: "registryId",
        type: "TEXT",
        nullable: false,
        description: "Stable registry identifier (for example openai_curated).",
      },
      {
        name: "registryLabel",
        type: "TEXT",
        nullable: false,
        description: "Registry display label.",
      },
      {
        name: "registryDescription",
        type: "TEXT",
        nullable: false,
        description: "Registry description text.",
      },
      {
        name: "repository",
        type: "TEXT",
        nullable: false,
        description: "Source repository in owner/name format.",
      },
      {
        name: "repositoryUrl",
        type: "TEXT",
        nullable: false,
        description: "Repository URL.",
      },
      {
        name: "sourcePath",
        type: "TEXT",
        nullable: false,
        description: "Path inside the repository used as registry source root.",
      },
      {
        name: "installDirectoryName",
        type: "TEXT",
        nullable: false,
        description: "Directory name used under app-data skills for this registry.",
      },
    ],
  },
  {
    tableName: "WorkspaceSkillProfile",
    toolName: "debug_read_workspace_skill_profile_table",
    purpose:
      "Stores per-user Skill master rows normalized by Skill location and linked to optional Skill registry masters.",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "INTEGER",
        nullable: false,
        description: "Internal auto-increment primary key.",
      },
      {
        name: "userId",
        type: "INTEGER",
        nullable: false,
        description: "Foreign key to WorkspaceUser.id.",
      },
      {
        name: "registryProfileId",
        type: "INTEGER",
        nullable: true,
        description: "Foreign key to WorkspaceSkillRegistryProfile.id when the Skill came from a registry.",
      },
      {
        name: "name",
        type: "TEXT",
        nullable: false,
        description: "Skill display name.",
      },
      {
        name: "location",
        type: "TEXT",
        nullable: false,
        description: "Skill source path or URI.",
      },
      {
        name: "source",
        type: "TEXT",
        nullable: false,
        description: "Skill source kind (for example codex_home or app_data).",
      },
    ],
  },
  {
    tableName: "Thread",
    toolName: "debug_read_thread_table",
    purpose:
      "Stores thread-level metadata and runtime options (name, timestamps, reasoning mode, web search toggle, instruction context toggles, thread environment variables).",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "TEXT",
        nullable: false,
        description: "Thread ID.",
      },
      {
        name: "userId",
        type: "INTEGER",
        nullable: false,
        description: "Foreign key to WorkspaceUser.id.",
      },
      {
        name: "name",
        type: "TEXT",
        nullable: false,
        description: "Editable thread title.",
      },
      {
        name: "createdAt",
        type: "TEXT",
        nullable: false,
        description: "Creation timestamp (ISO string).",
      },
      {
        name: "updatedAt",
        type: "TEXT",
        nullable: false,
        description: "Last updated timestamp (ISO string).",
      },
      {
        name: "deletedAt",
        type: "TEXT",
        nullable: true,
        description: "Archive timestamp when thread is soft-deleted.",
      },
      {
        name: "reasoningEffort",
        type: "TEXT",
        nullable: false,
        description: "Reasoning effort option for model execution.",
      },
      {
        name: "webSearchEnabled",
        type: "BOOLEAN",
        nullable: false,
        description: "Whether web-search-preview is enabled for the thread.",
      },
      {
        name: "threadEnvironmentJson",
        type: "TEXT",
        nullable: false,
        description: "Serialized thread-scoped environment variables JSON shared across turns.",
      },
      {
        name: "instructionContextTogglesJson",
        type: "TEXT",
        nullable: false,
        description:
          "Serialized instruction-context toggle map JSON (for example `{\\\"system\\\":true}`) controlling hidden context injection per thread.",
      },
    ],
  },
  {
    tableName: "ThreadSkillActivation",
    toolName: "debug_read_thread_skill_activation_table",
    purpose:
      "Stores ordered thread skill selections by linking each thread position to a workspace skill master row.",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "TEXT",
        nullable: false,
        description: "Skill selection row ID.",
      },
      {
        name: "threadId",
        type: "TEXT",
        nullable: false,
        description: "Foreign key to Thread.id.",
      },
      {
        name: "selectionOrder",
        type: "INTEGER",
        nullable: false,
        description: "Order of selected skills in the thread.",
      },
      {
        name: "skillProfileId",
        type: "INTEGER",
        nullable: false,
        description: "Foreign key to WorkspaceSkillProfile.id.",
      },
    ],
  },
  {
    tableName: "ThreadInstruction",
    toolName: "debug_read_thread_instruction_table",
    purpose: "Stores per-thread system instruction text edited in Threads tab.",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "INTEGER",
        nullable: false,
        description: "Internal auto-increment primary key.",
      },
      {
        name: "threadId",
        type: "TEXT",
        nullable: false,
        description: "Foreign key to Thread.id (unique; one instruction per thread).",
      },
      {
        name: "content",
        type: "TEXT",
        nullable: false,
        description: "Instruction body text.",
      },
    ],
  },
  {
    tableName: "ThreadMessage",
    toolName: "debug_read_thread_message_table",
    purpose:
      "Stores ordered chat messages per thread, including role, content, turn ID, and serialized attachments.",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "TEXT",
        nullable: false,
        description: "Message ID.",
      },
      {
        name: "threadId",
        type: "TEXT",
        nullable: false,
        description: "Foreign key to Thread.id.",
      },
      {
        name: "conversationOrder",
        type: "INTEGER",
        nullable: false,
        description: "Message order within the thread.",
      },
      {
        name: "role",
        type: "TEXT",
        nullable: false,
        description: "Chat role (user or assistant).",
      },
      {
        name: "content",
        type: "TEXT",
        nullable: false,
        description: "Message body text.",
      },
      {
        name: "createdAt",
        type: "TEXT",
        nullable: false,
        description: "Message creation timestamp (ISO string).",
      },
      {
        name: "turnId",
        type: "TEXT",
        nullable: false,
        description: "Turn identifier shared by message and MCP logs.",
      },
      {
        name: "attachmentsJson",
        type: "TEXT",
        nullable: false,
        description: "Serialized attachment list JSON.",
      },
    ],
  },
  {
    tableName: "ThreadMessageSkillActivation",
    toolName: "debug_read_thread_message_skill_activation_table",
    purpose:
      "Stores ordered message skill activation selections by linking each message position to a workspace skill master row.",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "TEXT",
        nullable: false,
        description: "Message skill activation row ID.",
      },
      {
        name: "messageId",
        type: "TEXT",
        nullable: false,
        description: "Foreign key to ThreadMessage.id.",
      },
      {
        name: "selectionOrder",
        type: "INTEGER",
        nullable: false,
        description: "Order of selected message skill activations in the message.",
      },
      {
        name: "skillProfileId",
        type: "INTEGER",
        nullable: false,
        description: "Foreign key to WorkspaceSkillProfile.id.",
      },
    ],
  },
  {
    tableName: "ThreadMcpConnection",
    toolName: "debug_read_thread_mcp_connection_table",
    purpose:
      "Stores MCP server connections that were active for a specific thread snapshot.",
    accumulatesErrors: false,
    fields: [
      {
        name: "id",
        type: "TEXT",
        nullable: false,
        description: "Thread MCP server row ID.",
      },
      {
        name: "threadId",
        type: "TEXT",
        nullable: false,
        description: "Foreign key to Thread.id.",
      },
      {
        name: "selectionOrder",
        type: "INTEGER",
        nullable: false,
        description: "Order of MCP servers attached to the thread.",
      },
      {
        name: "name",
        type: "TEXT",
        nullable: false,
        description: "Server display name at snapshot time.",
      },
      {
        name: "transport",
        type: "TEXT",
        nullable: false,
        description: "Transport type: streamable_http, sse, or stdio.",
      },
      {
        name: "url",
        type: "TEXT",
        nullable: true,
        description: "Remote endpoint URL for HTTP/SSE transports.",
      },
      {
        name: "headersJson",
        type: "TEXT",
        nullable: true,
        description: "Serialized custom HTTP headers JSON.",
      },
      {
        name: "useAzureAuth",
        type: "BOOLEAN",
        nullable: false,
        description: "Whether bearer token injection with DefaultAzureCredential is enabled.",
      },
      {
        name: "azureAuthScope",
        type: "TEXT",
        nullable: true,
        description: "Azure token scope used when useAzureAuth is true.",
      },
      {
        name: "timeoutSeconds",
        type: "INTEGER",
        nullable: true,
        description: "Per-server timeout in seconds for remote transports.",
      },
      {
        name: "command",
        type: "TEXT",
        nullable: true,
        description: "Executable command when transport is stdio.",
      },
      {
        name: "argsJson",
        type: "TEXT",
        nullable: true,
        description: "Serialized stdio command arguments JSON.",
      },
      {
        name: "cwd",
        type: "TEXT",
        nullable: true,
        description: "Working directory for stdio transport.",
      },
      {
        name: "envJson",
        type: "TEXT",
        nullable: true,
        description: "Serialized environment variable map JSON for stdio transport.",
      },
    ],
  },
  {
    tableName: "ThreadOperationLog",
    toolName: "debug_read_thread_operation_log_table",
    purpose:
      "Stores MCP RPC request/response logs for each thread and turn, including explicit error flags.",
    accumulatesErrors: true,
    fields: [
      {
        name: "rowId",
        type: "TEXT",
        nullable: false,
        description: "MCP log row ID.",
      },
      {
        name: "sourceRpcId",
        type: "TEXT",
        nullable: false,
        description: "Original RPC identifier from runtime history.",
      },
      {
        name: "threadId",
        type: "TEXT",
        nullable: false,
        description: "Foreign key to Thread.id.",
      },
      {
        name: "conversationOrder",
        type: "INTEGER",
        nullable: false,
        description: "Persisted ordering index used for thread replay.",
      },
      {
        name: "sequence",
        type: "INTEGER",
        nullable: false,
        description: "RPC sequence number within a run.",
      },
      {
        name: "operationType",
        type: "TEXT",
        nullable: false,
        description: "Operation category (mcp or skill).",
      },
      {
        name: "serverName",
        type: "TEXT",
        nullable: false,
        description: "MCP server name.",
      },
      {
        name: "method",
        type: "TEXT",
        nullable: false,
        description: "JSON-RPC method (for example tools/list or tools/call).",
      },
      {
        name: "startedAt",
        type: "TEXT",
        nullable: false,
        description: "RPC start timestamp (ISO string).",
      },
      {
        name: "completedAt",
        type: "TEXT",
        nullable: false,
        description: "RPC completion timestamp (ISO string).",
      },
      {
        name: "requestJson",
        type: "TEXT",
        nullable: false,
        description: "Serialized JSON-RPC request payload.",
      },
      {
        name: "responseJson",
        type: "TEXT",
        nullable: false,
        description: "Serialized JSON-RPC response payload.",
      },
      {
        name: "isError",
        type: "BOOLEAN",
        nullable: false,
        description: "True when the MCP RPC completed with an error.",
      },
      {
        name: "turnId",
        type: "TEXT",
        nullable: false,
        description: "Conversation turn identifier linked to the log.",
      },
    ],
  },
  {
    tableName: "RuntimeEventLog",
    toolName: "debug_read_runtime_event_log_table",
    purpose:
      "Stores server/client observability events, including errors and warnings used for diagnostics.",
    accumulatesErrors: true,
    fields: [
      {
        name: "id",
        type: "TEXT",
        nullable: false,
        description: "Event row ID.",
      },
      {
        name: "createdAt",
        type: "TEXT",
        nullable: false,
        description: "Event timestamp (ISO string).",
      },
      {
        name: "source",
        type: "TEXT",
        nullable: false,
        description: "Event source (for example server or client).",
      },
      {
        name: "level",
        type: "TEXT",
        nullable: false,
        description: "Log level (info, warning, error).",
      },
      {
        name: "category",
        type: "TEXT",
        nullable: false,
        description: "Log category.",
      },
      {
        name: "eventName",
        type: "TEXT",
        nullable: false,
        description: "Structured event name.",
      },
      {
        name: "message",
        type: "TEXT",
        nullable: false,
        description: "Human-readable log message.",
      },
      {
        name: "errorName",
        type: "TEXT",
        nullable: true,
        description: "Error class/name when available.",
      },
      {
        name: "location",
        type: "TEXT",
        nullable: true,
        description: "Source location (module/function context).",
      },
      {
        name: "action",
        type: "TEXT",
        nullable: true,
        description: "Action label associated with this event.",
      },
      {
        name: "statusCode",
        type: "INTEGER",
        nullable: true,
        description: "HTTP status code when applicable.",
      },
      {
        name: "httpMethod",
        type: "TEXT",
        nullable: true,
        description: "HTTP method for request-scoped logs.",
      },
      {
        name: "httpPath",
        type: "TEXT",
        nullable: true,
        description: "HTTP path for request-scoped logs.",
      },
      {
        name: "threadId",
        type: "TEXT",
        nullable: true,
        description: "Thread ID associated with the event.",
      },
      {
        name: "tenantId",
        type: "TEXT",
        nullable: true,
        description: "Azure tenant ID when available.",
      },
      {
        name: "principalId",
        type: "TEXT",
        nullable: true,
        description: "Azure principal/object ID when available.",
      },
      {
        name: "userId",
        type: "INTEGER",
        nullable: true,
        description: "WorkspaceUser.id when available.",
      },
      {
        name: "stack",
        type: "TEXT",
        nullable: true,
        description: "Stack trace text for error events.",
      },
      {
        name: "contextJson",
        type: "TEXT",
        nullable: false,
        description: "Serialized structured context payload.",
      },
    ],
  },
  {
    tableName: "SkillRegistryCache",
    toolName: "debug_read_skill_registry_cache_table",
    purpose:
      "Stores cached skill-registry payload snapshots and expiration timestamps.",
    accumulatesErrors: false,
    fields: [
      {
        name: "cacheKey",
        type: "TEXT",
        nullable: false,
        description: "Cache key for registry payload lookup.",
      },
      {
        name: "payloadJson",
        type: "TEXT",
        nullable: false,
        description: "Serialized registry payload JSON.",
      },
      {
        name: "updatedAt",
        type: "TEXT",
        nullable: false,
        description: "Cache update timestamp (ISO string).",
      },
      {
        name: "expiresAt",
        type: "TEXT",
        nullable: false,
        description: "Cache expiration timestamp (ISO string).",
      },
    ],
  },
];
